{{- if eq .Values.mode "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlops-serving.fullname" . }}
  labels:
    {{- include "mlops-serving.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlops-serving.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlops-serving.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MODEL_PATH
              value: {{ .Values.model.path | quote }}
            {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or .Values.secret.create .Values.deployment.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ default (include "mlops-serving.secretName" .) .Values.deployment.envFromSecret }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.path }}
              port: {{ .Values.deployment.containerPort }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path }}
              port: {{ .Values.deployment.containerPort }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: model-storage
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: {{ include "mlops-serving.pvcName" . }}
      {{- end }}
{{- end }}
