{{- if and (eq .Values.mode "deployment") .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops-serving.fullname" . }}
  labels:
    {{- include "mlops-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mlops-serving.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- end }}
